macOS configuration options for using only the left or right alt key …
neovide/neovide pull request #1979
Opened 2023-08-15 18:42 UTC by apettel

…as meta

## What kind of change does this PR introduce?
- Feature

I'm using the [EurKEY Keyboard Layout](https://eurkey.steffen.bruentjen.eu/?lang=en). To access certain characters (e.g. ä, ö, ü, ß) I need the alt key. But I also need the alt key as meta key for certain terminal applications. 
I configured the right alt key in my terminal program to switch the characters in the EurKEY-Layout and the left alt key is used as meta key. I created a patch for neovide to allow the separate configuration of the right and the left alt key (branch: macos-left-right-alt-meta).

## Did this PR introduce a breaking change? 
- No

2023-08-15 20:04 UTC, fredizzimo commented
Thanks, but this should be implemented using the native Winit `OptionAsAlt`  https://github.com/rust-windowing/winit/pull/2887

The only reason why it wasn't implemented like that before is that it came when this was almost finished https://github.com/neovide/neovide/pull/1899. And because I don't have a mac to test on, I did not want to risk anything.

If you implement it using that, I think all, at least almost all the macOS specific stuff in `keyboard_manager.rs` can be removed.

2023-08-15 20:10 UTC, fredizzimo commented
This is the relevant issue for this PR https://github.com/neovide/neovide/issues/1877

And it might also fix this issue (that needs to be tested)
https://github.com/neovide/neovide/issues/1866

2023-08-18 10:20 UTC, uloco commented
omg i need this so badly, typing on a german layout makes using neovide impossible right now without this. hope this gets merged soon. thank you!

2023-08-18 10:52 UTC, fredizzimo requested changes
I'm making it more explicit that this won't be approved until it's re-implemented with `OptionAsAlt ` as described in the first message.

Note, that I'm very happy to see this being done and worked on and I don't see anything specifically wrong with this implementation. It's just that we don't want to maintain and duplicate work that's already done in Winit, and we also want to avoid special cases for different operating systems where possible.

2024-04-23 18:57 UTC, closed without merging

2024-04-23 18:57 UTC, fredizzimo commented
An alternative implementation was done here
* https://github.com/neovide/neovide/pull/2486