on macOS, activate when launched
neovide/neovide pull request #2799
Opened 2024-09-20 17:42 UTC by fboundp

Generally, it is considered bad form for an application to un-cooperatively take the focus. However, for applications that are frequently launched from the terminal, they must strongly request focus because the terminal, in its ignorance, will not automatically yield.

## What kind of change does this PR introduce?
- Fix: Fixes #2330 

## Did this PR introduce a breaking change? 
- No

2024-09-20 21:31 UTC, falcucci requested changes
Unfortunately this didn't work to me, at macOS Sonoma.

I'll dig into it to help to fix this once there are a couple of people willing this fix.

*The focus issue only happens when launched exclusively from bundled neovide tho. It means that if you use the common build binary you are safe from this issue.*

2024-09-23 14:59 UTC, fboundp commented
> Unfortunately this didn't work to me, at macOS Sonoma.

Whoops, that’s because while teasing apart my local branch into PRs I cherry picked an earlier version. 🤦‍♂️
Force pushed a mixup.

2024-09-23 15:55 UTC, falcucci approved these changes
@fboundp thank you, that works great now!

2024-09-23 15:55 UTC, merged

2024-09-23 20:10 UTC, fredizzimo commented
There's something strange going on here if this fixes the issue. 

Winit is supposed to set `with_activate_ignoring_other_apps` to true by default
https://docs.rs/winit/latest/x86_64-apple-darwin/winit/platform/macos/trait.EventLoopBuilderExtMacOS.html#tymethod.with_activate_ignoring_other_apps

Which does this https://github.com/rust-windowing/winit/blob/114512bb329ac2da78e33dcd54c3f466f34da394/src/platform_impl/macos/app_state.rs#L118

As far as I can see, that does the exact same thing as this PR. And it would be much better if we could use Winit for this to reduce the maintainance burden.

Therefore, I think it would be worth investigating why it's not working, and possibly create a Winit bug report.

2024-09-23 21:02 UTC, falcucci commented
@fredizzimo that was indeed weird but once this issue started to bother a lot, I guess that getting this fixed as soon as possible, was better. I have done some tests using the same method `with_activate_ignoring_other_apps` that winit exposes but it didn't work.

2024-09-23 21:04 UTC, falcucci commented
I am checking if this is something that works for specific enabled features only.

2024-09-23 21:11 UTC, fredizzimo commented
It's probably some initialization order thing, maybe we initialize something at the wrong point, overriding stuff from winit.

2024-09-23 21:25 UTC, fboundp commented
Oh yeah, good find @fredizzimo. winit even appears to trigger it in the `applicationDidFinishLaunching:` notification that I couldn’t figure out how to line up with. You are probably onto something about the initialization ordering; it took me a couple of tries to find a spot in Neovide itself where the `activateIgnoringOtherApps` call was effective.

2024-10-04 05:17 UTC, sdfgsdfgd commented
hi is there going to be a release for this fix pls

2024-10-04 12:14 UTC, falcucci commented
@sdfgsdfgd yes, release is coming very soon.